postgresql:
  restart: always
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
gitlab:
  restart: always
  image: sameersbn/gitlab:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:10080"
    - "10022:10022"
  environment:
    - DEBUG=false
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=
redis:
  restart: always
  image: sameersbn/redis:latest
  command:
    - --loglevel warning
